name: Release

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  cd:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 18
          check-latest: true

      - name: Install dependencies
        run: npm isntall

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
