name: Test

on:
  push:
  pull_request:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Capture eslint errors
        run: npx eslint --no-ignore -f compact test/** | sed -E 's/^.*(eslint-config.*)$/\1/g' > found.txt || true

      - name: Check for differences
        run: diff found.txt .github/eslint-errors.txt
